### ISSUE TITLE
This doesn't work anymore

### ISSUE THREAD

**Issue by BTSpaniel** [Beskhue/discord-voice-log-bot#1]
Can you please fix it?

**Comment by tomcur** [comment]
What issue are you encountering?

**Comment by BTSpaniel** [comment]
I'm not really a good python coder yet, but from what i found the problem lies in: 

Note that in Python 3.4 you use @asyncio.coroutine instead of async def and yield from instead of await.

Source: https://github.com/Rapptz/discord.py

**Comment by BTSpaniel** [comment]
I think i was using the wrong python version. Sorry.

**Comment by tomcur** [comment]
That is possible, the bot requires Python 3.5 due to `async` and `await` syntax.
